[uwsgi]
module = app:app

master = true
processes = 4
;protocol = http

uid = www-data
gid = www-data

socket = 127.0.0.1:5000
;chmod-socket = 660
vacuum = true

die-on-term = true

plugins = python3
