"""add adults, children, children_under_five to booking

Revision ID: e1e1e3028bb5
Revises: 6ded896542db
Create Date: 2026-02-01 18:09:06.791728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e1e3028bb5'
down_revision: Union[str, Sequence[str], None] = '6ded896542db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('adults', sa.Integer(), server_default='0', nullable=False))
    op.add_column('booking', sa.Column('children', sa.Integer(), server_default='0', nullable=False))
    op.add_column('booking', sa.Column('children_under_five', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'children_under_five')
    op.drop_column('booking', 'children')
    op.drop_column('booking', 'adults')
    # ### end Alembic commands ###
